# Generated by Django 5.2.7 on 2025-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('release_year', models.CharField(blank=True, max_length=4)),
                ('poster_url', models.URLField(blank=True)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
