# Generated by Django 5.2.7 on 2025-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='release_year',
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='genre_ids',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='release_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='poster_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
    ]
