# Generated by Django 5.2.7 on 2025-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_favoritemovie_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
